### ISSUE TITLE
No door found?

### ISSUE THREAD

**Issue by CelticWebSolutions** [luisiam/homebridge-liftmaster2#17]
I get the following error

[2/11/2017, 10:19:40 AM] Logged in with MyQ user ID 0
[2/11/2017, 10:19:41 AM] Error 'Error: EACCES: permission denied, open '/Users/server/.homebridge/accessories/cachedAccessories''
[2/11/2017, 10:19:41 AM] Error: Couldn't find a MyQ door device.

Any idea what the issue could be please?

**Comment by sohnkarlsruhe** [comment]
Try with root right: sudo homebridge

**Comment by RossGGG** [comment]
I am getting the "Couldn't find a MyQ door device." error as well with the newest version.  I am able to use the myQ app without any issue.

**Comment by FlippedBitSolutions** [comment]
I am also getting the "Couldn't find a MyQ door device." error using version 0.4.2

**Comment by luisiam** [comment]
Please include a full log here

**Comment by FlippedBitSolutions** [comment]
[homebridge.log.zip](https://github.com/luisiam/homebridge-liftmaster2/files/795338/homebridge.log.zip)

**Comment by RossGGG** [comment]
[homebridge.log.zip](https://github.com/luisiam/homebridge-liftmaster2/files/795725/homebridge.log.zip)

**Comment by RossGGG** [comment]
I have been debugging the plugin code and found where the problem is occurring, but I'm not sure what the problematic code is meant to do so I haven't tried changing it.

In the case of my opener the problem occurs at **line 273** of index.js: if (thisDoorMonitor === "0").  The rest of the code that sets up the opener accessory and confirms that we have valid data lives inside this condition block.

In my case, **thisDoorMonitor** will equal **1** since that is what it is set to on **line 252** and the only time it could be changed to 0 is at **lines 268-269** when it is set to the value of the **myqmonitormode** attribute returned by the myQ api.  The problem is that the attributes for my opener **does not include an attribute named "myqmonitormode"**.  Why exactly are you checking for this attribute?

Here is a list of the attributes my garage door opener has from the myQ api:
'online', 'gatewayID', 'desc', 'doorstate', 'addedtime', 'isunattendedopenallowed', 'isunattendedcloseallowed', 'name', 'customerName'

**Comment by erfinb** [comment]
I'm experiencing the same issue here... how can we fix this? :)

**Comment by luisiam** [comment]
Please try the latest version 0.4.3

**Comment by erfinb** [comment]
Sorry, just updated and we are back in action.

**Comment by AndreasMenrad** [comment]
I just configured it and having this issue, can’t find the door, but it is in MyQ.
I run homebridge on my Synology (Docker). 
Any help is greatly appreciated. 
[marcoraddatz-homebridge.pdf](https://github.com/luisiam/homebridge-liftmaster2/files/1735357/marcoraddatz-homebridge.pdf)
